ALTER TABLE "Listing" ADD COLUMN "make" TEXT NOT NULL DEFAULT 'Toyota';
ALTER TABLE "Listing" ADD COLUMN "model" TEXT NOT NULL DEFAULT 'Camry';
ALTER TABLE "Listing" ADD COLUMN "year" INTEGER NOT NULL DEFAULT 2020;
